services:
  app:
    build:
      context: .
    expose:
      - "3001-3017" # Expose a range of ports

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/generated:/usr/src/app/nginx/generated
    ports:
      - "80:80"
    depends_on:
      - app
